// <auto-generated />
namespace BoVoyage.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TravelWithoutUnique : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TravelWithoutUnique));
        
        string IMigrationMetadata.Id
        {
            get { return "201810130030211_TravelWithoutUnique"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
